In [25]:
import numpy as np

In [26]:
A = np.array([[1, 2, -1],
    [2, -3, 1],
    [5, -1, -2]])
B = np.array([[2],
             [-1],
             [-3]])

In [27]:
print(A)

[[ 1  2 -1]
 [ 2 -3  1]
 [ 5 -1 -2]]


In [28]:
print(B)

[[ 2]
 [-1]
 [-3]]


In [29]:
#transpose matrix A
print(A.transpose())

[[ 1  2  5]
 [ 2 -3 -1]
 [-1  1 -2]]


In [30]:
#find the product of 2 matrices
print(A.dot(B))

[[ 3]
 [ 4]
 [17]]


In [31]:
#determinant of matrix A
DetA = (A[0][0]*((A[1][1]*A[2][2])-(A[1][2]*A[2][1])))-(A[0][1]*((A[1][0]*A[2][2])-(A[1][2]*A[2][0])))+(A[0][2]*((A[1][0]*A[2][1])-(A[1][1]*A[2][0])))
print(DetA)

12


In [50]:
#inverse of matrix A
print("Matrix A")
print(A)
print()

##find determinant of matrix A
print("Determinant of matrix A")
DetA = (A[0][0]*((A[1][1]*A[2][2])-(A[1][2]*A[2][1])))-(A[0][1]*((A[1][0]*A[2][2])-(A[1][2]*A[2][0])))+(A[0][2]*((A[1][0]*A[2][1])-(A[1][1]*A[2][0])))
print(DetA)
print()

##transpose matrix A
print("Transpose of matrix A")
C = A.transpose()
print(C)
print()

#find the determinant of each of the 2x2 minor matrices
print("Determinant of each of the 2x2 minor in transpose matrix A")
a = (C[1][1]*C[2][2])-(C[1][2]*C[2][1])
b = (C[1][0]*C[2][2])-(C[1][2]*C[2][0])
c = (C[1][0]*C[2][1])-(C[1][1]*C[2][0])
d = (C[0][1]*C[2][2])-(C[0][2]*C[2][1])
e = (C[0][0]*C[2][2])-(C[0][2]*C[2][0])
f = (C[0][0]*C[2][1])-(C[0][1]*C[2][0])
g = (C[0][1]*C[1][2])-(C[0][2]*C[1][1])
h = (C[0][0]*C[1][2])-(C[0][2]*C[1][0])
i = (C[0][0]*C[1][1])-(C[0][1]*C[1][0])
D = np.array([[a, b, c],
             [d, e, f],
             [g, h, i]])
print(D)
print()

#create the matrix of cofactors
print("Create the matrix of cofactors for find adjoint of matrix A")
D = np.array([[a, b*-1, c],
             [d*-1, e, f*-1],
             [g, h*-1, i]])
print(D)
print()

#find inverse of matrix A
print("Inverse of matrix A")
E = (1/DetA)*D
print(E)

Matrix A
[[ 1  2 -1]
 [ 2 -3  1]
 [ 5 -1 -2]]

Determinant of matrix A
12

Transpose of matrix A
[[ 1  2  5]
 [ 2 -3 -1]
 [-1  1 -2]]

Determinant of each of the 2x2 minor in transpose matrix A
[[  7  -5  -1]
 [ -9   3   3]
 [ 13 -11  -7]]

Create the matrix of cofactors for find adjoint of matrix A
[[ 7  5 -1]
 [ 9  3 -3]
 [13 11 -7]]

Inverse of matrix A
[[ 0.58333333  0.41666667 -0.08333333]
 [ 0.75        0.25       -0.25      ]
 [ 1.08333333  0.91666667 -0.58333333]]


In [56]:
#matrix A
print("Matrix A")
print(A)
print()

#find the determinant of each of the 2x2 minor matrices
print("Determinant of each of the 2x2 minor of matrix A")
a = (A[1][1]*A[2][2])-(A[1][2]*A[2][1])
b = (A[1][0]*A[2][2])-(A[1][2]*A[2][0])
c = (A[1][0]*A[2][1])-(A[1][1]*A[2][0])
d = (A[0][1]*A[2][2])-(A[0][2]*A[2][1])
e = (A[0][0]*A[2][2])-(A[0][2]*A[2][0])
f = (A[0][0]*A[2][1])-(A[0][1]*A[2][0])
g = (A[0][1]*A[1][2])-(A[0][2]*A[1][1])
h = (A[0][0]*A[1][2])-(A[0][2]*A[1][0])
i = (A[0][0]*A[1][1])-(A[0][1]*A[1][0])
minorA = np.array([[a, b, c],
             [d, e, f],
             [g, h, i]])
print(minorA)
print()

#create the matrix of cofactors
print("Create the matrix for find cofactors of matrix A")
coA = np.array([[a, b*-1, c],
             [d*-1, e, f*-1],
             [g, h*-1, i]])
print(coA)
print()

#find adjoint of matrix A by transpose cofactor of matrix A
print("Adjoint of matrix A")
adjA = coA.transpose()
print(adjA)

Matrix A
[[ 1  2 -1]
 [ 2 -3  1]
 [ 5 -1 -2]]

Determinant of each of the 2x2 minor of matrix A
[[  7  -9  13]
 [ -5   3 -11]
 [ -1   3  -7]]

Create the matrix for find cofactors of matrix A
[[ 7  9 13]
 [ 5  3 11]
 [-1 -3 -7]]

Adjoint of matrix A
[[ 7  5 -1]
 [ 9  3 -3]
 [13 11 -7]]
