In [1]:
# ln (x) question
def ln(x):
    x = 1-x
    pre = 0
    result = -x
    i = 2
    while pre - result > 0.00001:
        pre = result
        result -= pow(x,i) / i
        i = i+1
    return result
ln(0.8)

-0.22314316190476188

In [2]:
# 4 iterations
def lniter4(x):
    x = 1-x
    result = -x
    for i in range(2,4) :
        result -= pow(x,i) / i
    return result
lniter4(0.8)

-0.22266666666666662

In [3]:
# square root appox
def squareroot(x) :
    n = 1
    result = (n + x/n) / 2
    while abs(n - result) > 0.0000001:
        n = result
        result = (n + x/n) / 2
    return result
squareroot(2)

1.414213562373095

In [4]:
# square root 4 iter
def squarerootiter4(x) :
    n = 1
    result = (n + x/n) / 2
    for i in range(2,4):
        n = result
        result = (n + x/n) / 2
    return result
squareroot(3)

1.7320508075688772

In [35]:
import numpy as np
linsys = np.array([[1,2,-1],[2,-3,1],[5,-1,-2]], dtype='float')
b = np.array([[2],[-1],[-3]])

In [36]:
def inversesolve(x, b) :
    y = np.linalg.inv(x)
    return np.dot(y,b)
inversesolve(linsys, b)

array([[ 1.],
       [ 2.],
       [ 3.]])

In [37]:
def gausselimate(x, b) :
    result = np.hstack((x,b))
    n = len(result)
    for i in range(n):
        a = result[i]
    for j in range(i + 1, n):
        b = result[j]
        m = a[i] / b[i]
        result[j] = a - m * b

    for i in range(n - 1, -1, -1):
        result[i] = result[i] / result[i, i]
        a = result[i]
        for j in range(i - 1, -1, -1):
            b = result[j]
            m = a[i] / b[i]
            result[j] = a - m * b
    return result[:, 3]
gausselimate(linsys, b)

array([ 1.        ,  0.71428571,  1.5       ])

In [29]:
ab = np.hstack((linsys, b))
print(ab)

[[ 1  2 -1  2]
 [ 2 -3  1 -1]
 [ 5 -1 -2 -3]]


In [27]:
print((linsys[1], b[1]))

(array([ 2, -3,  1]), array([-1]))


In [31]:
len(ab[0])

4